<h1><img src="/img/supplier/header.png" width="50" /> <?php  echo $this->translate("Supplier") ?></h1>

<a class="back" href="<?php echo $this->url('supplier', array('section' => $section)) ?>" >
    <img src="/img/content/back.png" /><?php echo $this->translate("Back")?></a>
<div class="options">
    <a class="supplier edit" href="<?php echo $this->url('supplier-edit', array('id' => $supplier->getId(), 'section' => $section));?>">
        <img src="/img/supplier/edit.png" /><?php echo $this->translate("Edit")?></a>
    <div class="supplier delete" data-id="<?php echo $supplier->getId() ?>" data-section="<?php echo $section ?>" >
        <img src="/img/supplier/del.png" /><?php echo $this->translate("Delete")?></div>
</div>
<div class="error-message supplier"></div>
<?php
    $name = $supplier->getName();
    $address = $supplier->getAddress();
    $phone = $supplier->getPhone();
    $email = $supplier->getEmail();
    $website = $supplier->getWebsite();
?>
<div class="details supplier">
    <dl>
        <?php if(!empty($name)) { ?>
            <dt><?php echo $this->translate("Name") ?>:</dt>
            <dd><?php echo $name ?></dd>
        <?php
        }
        ?>
        <?php if(!empty($address)){ ?>
            <dt><?php echo $this->translate("Address") ?>:</dt>
            <dd><?php echo nl2br($address) ?></dd>
        <?php
        }
        ?>
    </dl>
    <dl>
        <?php if(!empty($phone)){ ?>
            <dt><?php echo $this->translate("Phone") ?>:</dt>
            <dd><?php echo $phone ?></dd>
        <?php
        }
        ?>
    </dl>
    <dl>
        <?php if(!empty($email)){ ?>
            <dt><?php echo $this->translate("Email") ?>:</dt>
            <dd><a href="mailto:<?php echo $email ?>" ><?php echo $email ?></a></dd>
        <?php
        }
        ?>
        <?php if(!empty($website)){ ?>
            <dt><?php echo $this->translate("Website") ?>:</dt>
            <dd><a target="_blank" href="<?php echo $website ?>" ><?php echo $website ?></a></dd>
        <?php
        }
        ?>
    </dl>
</div>


<?php
    foreach($productsGrouped as $type => $products){
?>
        <div class="product-list">
<?php
        echo $this->partial('productList', array(
            'products' => $products,
            'productType' => $productsTypes[$type],
            'supplier' => $supplier,
            'section' => $this->sectionName(),
        ));
?>
        </div>
<?php
    }

$this->placeholder('scripts')->append("
        BowsManager.supplier.del();
    ");
?>