<?php
use Supplier\Model\Supplier;
use Supplier\Enum\SupplierEnum;
?>
<h1>
    <img src="/img/bill/header.png" width='80' /> <?php echo $this->translate("Suppliers List"); ?>
</h1>
<div class="options">
    <div class="supplier add" data-section="<?php echo $section ?>" ><img src="/img/bill/add.png" /><?php echo $this->translate("Add new supplier") ?></div>
</div>
<div class="error-message supplier"></div>

<table class="table suppliers">
    <tr>
        <td colspan="3">
            <?php foreach(SupplierEnum::FILTERS() as $filter){ ?>
                <a href="#" class="supplier-filter" id="<?php echo $filter; ?>" ><?php echo $filter; ?></a>
            <?php } ?>
        </td>
    </tr>
<?php
        $firstLetter = null;
        /**  @var  $supplier Supplier*/
    foreach ($suppliers as $supplier) :
        $currentFirstLetter = strtolower($supplier->getName());
        if($currentFirstLetter[0] != $firstLetter){
            $firstLetter = $currentFirstLetter[0];
            ?>
            <tr class="data <?php echo $firstLetter ?>">
                <td colspan="3"><h3><?php echo strtoupper($firstLetter);?></h3></td>
            </tr>
        <?php
        }

        $detailUrl =  $this->url('supplier-details', array('id' => $supplier->getId()));
     ?>
        <tr class="data supplier <?php echo $firstLetter ?>" id="supplier-<?php echo $supplier->getId() ?>" data-url="<?php echo $detailUrl ?>" >
            <td><?php echo $supplier->getName(); ?></td>
            <td class="supplier-options">
                <div class="list-options" >
                    <div class="supplier delete" data-id="<?php echo $supplier->getId() ?>" ><img src="/img/bill/del.png" /><?php echo $this->translate("Delete") ?></div>
                    <div class="supplier edit" data-id="<?php echo $supplier->getId() ?>"  data-section="<?php echo $section ?>" ><img src="/img/bill/edit.png" /><?php echo $this->translate("Edit") ?></div>
                </div>
            </td>
        </tr>
<?php endforeach; ?>
</table>
<?php
$this->placeholder('scripts')->append("
        BowsManager.supplier.listInitFilters();
        BowsManager.supplier.details();
        BowsManager.supplier.del();
        BowsManager.supplier.add();
        BowsManager.supplier.edit();
    ");
?>