<?php
use Supplier\Model\Supplier;
use Application\Enum\SectionEnum;
?>
<h1>
    <img src="/img/bill/header.png" width='80' /> <?php echo $this->translate("Suppliers List"); ?>
</h1>
<div class="options">
    <div class="supplier add" data-section="<?php echo $section ?>" ><img src="/img/bill/add.png" /><?php echo $this->translate("Add new supplier") ?></div>
</div>
<div class="error-message supplier"></div>

<table class="table suppliers">
    <tr>
        <th><?php echo $this->translate("Name") ?></th>
        <th>&nbsp;</th>
    </tr>

    <?php /**  @var  $supplier Supplier*/?>
    <?php foreach ($suppliers as $supplier) :
        $detailUrl =  $this->url('client-details', array('id' => $client->getId()));
     ?>
        <tr class="supplier" id="supplier-<?php echo $supplier->getId() ?>" data-url="<?php echo $detailUrl ?>" >
            <td><?php echo $supplier->getName(); ?></td>
            <td class="supplier-options">
                <div class="list-options" >
                    <div class="supplier delete" data-id="<?php echo $supplier->getId() ?>" ><img src="/img/bill/del.png" /><?php echo $this->translate("Delete") ?></div>
                    <div class="supplier edit" data-id="<?php echo $supplier->getId() ?>"  data-section="<?php echo $section ?>" ><img src="/img/bill/edit.png" /><?php echo $this->translate("Edit") ?></div>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<?php
$this->placeholder('scripts')->append("
        BowsManager.supplier.details();
        BowsManager.supplier.del();
        BowsManager.supplier.add();
        BowsManager.supplier.edit();
    ");
?>