<?php
if($section == \Application\Enum\SectionEnum::COLLECTION_INDEX){
    $backUrl = $this->url('collection');
}
else {
    $backUrl = $this->url('client-details', array('id' => $collection->getOwnerId()));
}

echo $this->partial('formCollection', array(
    'header' => $this->translate("New Collection"),
    'collection' => $collection,
    'clients' => $clients,
    'backUrl' => $backUrl,
    'section' => $section,
));
