<h1><img src="/img/collection/header.png" width='80' /><?php echo $header ?></h1>
<a class="back" href="<?php echo $backUrl ?>" ><img src="/img/content/back.png">
<?php echo $this->translate("Back") ?></a>
<div class="error-message collection"></div>

<?php
    if(empty($clients) && $collection->getOwnerId() === null){
        echo $this->translate("Please add a client first!");
    }
    else {
?>
<form id="collection-form" enctype="multipart/form-data">
    <input type="hidden" name="section" value="<?php echo $section ?>">
    <input type="hidden" name="id" id="id" value="<?php echo $collection->getId() ?>">

    <label for="owner"><?php echo $this->translate("Client") ?></label><br/>
    <?php if(!empty($clients)){ ?>
        <select name="owner" id="owner">
    <?php
        /** @var $client \Client\Model\Client */
        foreach($clients as $client){
    ?>
        <option value="<?php echo $client->getId(); ?>"><?php echo $client->getName(); ?></option>
    <?php
        }
    ?>
        </select><br />
    <?php
    }
    else {
     ?>
        <input type="hidden" name="owner" value="<?php echo $collection->getOwnerId(); ?>" />
        <a href="<?php echo $this->url("client-details", array('id' => $collection->getOwnerId())) ?>" >
            <?php echo $collection->getOwnerName() ?>
        </a><br />
    <?php
    }
    ?>

    <label for="receptionTime"><?php echo $this->translate("Reception Date") ?></label><br/>
    <input type="text" name="receptionTime" class="datepicker" id="receptionTime" value="<?php echo $collection->getReceptionTime() ?>"><br>

    <label for="returnTime"><?php echo $this->translate("Return Date") ?></label><br/>
    <input type="text" name="returnTime" class="datepicker" id="returnTime" value="<?php echo $collection->getReturnTime() ?>"><br>

    <label for="packageNumber"><?php echo $this->translate("Package Number") ?></label><br/>
    <input type="text" name="packageNumber" id="packageNumber" value="<?php echo $collection->getPackageNumber() ?>"><br>

    <?php /*
    <ul>
        <li>
            <label for="billReference"><?php echo $this->translate("Bill Reference") ?></label><br/>
            <input type="text" name="billReference" id="billReference" value="<?php echo $collection->getBillReference() ?>">
        </li>
        <li>
            <label for="attachment"><?php echo $this->translate("Add Attachments") ?></label><br />
            <input type="file" name="attachment" id="bill-attachment" multiple ><br />
        </li>
        <?php if($collection->hasAttachments()){?>
            <li>
                <label for="files"><?php echo $this->translate("Remove Attachments") ?></label><br />
                <?php foreach($collection->getAttachments() as $attachment) { ?>
                    <div>
                        <input type="checkbox" class="files" name="del-attachment[]" value="<?php echo $attachment ?>">
                        <a target="_blank"href="/img/attachment/<?php echo $attachment; ?>" >
                            <?php echo $this->fileType()->getOriginalName($attachment); ?>
                        </a>
                    </div>
                <?php } ?>
            </li>
        <?php } ?>
    </ul>
    <br class="clearfix" />

    <label for="billAmount"><?php echo $this->translate("Bill Amount") ?></label><br/>
    <input type="text" name="billAmount" id="billAmount" value="<?php echo $collection->getBillAmount() ?>"> €<br />

    <label for="paidStatus"><?php echo $this->translate("Is paid?") ?></label>
    <input type="checkbox" name="paidStatus" id="paidStatus" <?php echo $collection->isPaid() ? "checked='checked'": ""; ?> /><br>
*/ ?>
    <br/>
    <div id="save-collection">
        <button type="submit" ><?php echo $this->translate("Save") ?></button>
    </div>
</form>
<?php
    $this->placeholder('scripts')->append("
        BowsManager.tools.datepicker();
        BowsManager.tools.attachment.getData('#bill-attachment', BowsManager.collection);
        BowsManager.collection.add()
    ");
?>
<?php
    }
?>


