<h1><img src="/img/collection/header.png" width='80' /><?php echo $header ?></h1>
<a class="back" href="<?php echo $backUrl ?>" ><img src="/img/content/back.png">
<?php echo $this->translate("Back") ?></a>
<div class="error-message collection"></div>

<?php
    if(empty($clients) && $collection->getOwnerId() === null){
        echo $this->translate("Please add a client first!");
    }
    else {
?>

<form id="collection-form" enctype="multipart/form-data">
    <input type="hidden" name="section" value="<?php echo $section ?>">
    <input type="hidden" name="id" id="id" value="<?php echo $collection->getId() ?>">

    <label for="owner"><?php echo $this->translate("Client") ?></label><br/>

    <select name="owner" id="owner">
        <?php
        /** @var $client \Client\Model\Client */
        foreach($clients as $client){
            $selected = "";
            // if the owner is defined select it
            if($collection->getOwnerId() == $client->getId()) {
                $selected = "selected='selected'";
            }

            ?>
            <option value="<?php echo $client->getId(); ?>" <?php echo $selected ?> ><?php echo $client->getName(); ?></option>
        <?php
        }
        ?>
    </select><br />

    <label for="receptionTime"><?php echo $this->translate("Reception Date") ?></label><br/>
    <input type="text" name="receptionTime" class="datepicker" id="receptionTime" value="<?php echo $collection->getReceptionTime() ?>"><br>

    <label for="returnTime"><?php echo $this->translate("Return Date") ?></label><br/>
    <input type="text" name="returnTime" class="datepicker" id="returnTime" value="<?php echo $collection->getReturnTime() ?>"><br>

    <label for="packageNumber"><?php echo $this->translate("Package Number") ?></label><br/>
    <input type="text" name="packageNumber" id="packageNumber" value="<?php echo $collection->getPackageNumber() ?>"><br />

    <label for="comments"><?php echo $this->translate("Comments") ?></label><br/>
    <textarea type="text" name="comments" id="comments" ><?php echo $collection->getComments() ?></textarea><br />

    <br/>
    <div id="save-collection">
        <button type="submit" ><?php echo $this->translate("Save") ?></button>
    </div>
</form>
<?php
    $this->placeholder('scripts')->append("
        BowsManager.tools.datepicker();
        BowsManager.tools.attachment.getData('#bill-attachment', BowsManager.collection);
        BowsManager.collection.add()
    ");
?>
<?php
    }
?>
