<h1>
    <?php echo $header ?>
</h1>
<div class="error-message"></div>
<? /*
6	bill_reference	varchar(100)	utf8_general_ci		Non	Aucune		 Modifier Modifier	 Supprimer Supprimer	 plus Montrer d'autres actions
7	bill_amount	float			Non	Aucune		 Modifier Modifier	 Supprimer Supprimer	 plus Montrer d'autres actions
8	paid_status */
?>

<a href="<?php echo $backUrl ?>" >
    <?php echo $this->translate("Back") ?>
</a>
<form id="collection-form" >
    <input type="hidden" name="id" id="id" value="<?php echo $collection->getId() ?>"><br>

    <label for="owner"><?php echo $this->translate("Client") ?></label>
    <?php if(!empty($clients)){ ?>
        <select name="owner" id="owner">
    <?php
        /** @var $client \Client\Model\Client */
        foreach($clients as $client){
    ?>
        <option value="<?php echo $client->getId(); ?>"><?php echo $client->getName(); ?></option>
    <?php
        }
    ?>
        </select><br />
    <?php
    }
    else {
     ?>
        <input type="hidden" name="owner" value="<?php echo $client->getId(); ?>" />
        <a href="<?php echo $this->url("client", array('action'=>'details', 'id' => $collection->getOwnerId())) ?>" >
            <?php echo $collection->getOwnerName() ?>
        </a><br />
    <?php
    }
    ?>

    <label for="receptionTime"><?php echo $this->translate("Reception Date") ?></label>
    <input type="text" name="receptionTime" id="receptionTime" value="<?php echo $collection->getReceptionTime() ?>"><br>

    <label for="packageNumber"><?php echo $this->translate("Package Number") ?></label>
    <input type="text" name="packageNumber" id="packageNumber" value="<?php echo $collection->getPackageNumber() ?>"><br>

    <label for="returnTime"><?php echo $this->translate("Return Date") ?></label>
    <input type="text" name="returnTime" id="returnTime" value="<?php echo $collection->getReturnTime() ?>"><br>

    <button type="submit" id="save-collection" ><?php echo $this->translate("Save") ?></button>
</form>
<?php
    $this->placeholder('scripts')->append("BowsManager.collection.add()");
?>


