<?php
use Collection\Model\Collection;
use Collection\Enum\CollectionEnum;
?>
<h1><?php echo $this->translate('Collections'); ?></h1>
<p>
    <a href="<?php echo $this->url('collection', array('action'=>'add',
                                                        'id' => CollectionEnum::NEW_COLLECTION,
                                                        'clientId' => (isset($clientId)) ? $clientId : false,
        )
    );?>">
        <?php echo $this->translate("Add new collection"); ?>
    </a>
</p>

<table class="table">
    <th>
        <?php echo $this->translate("Reception Time"); ?>
    </th>
    <th>
        <?php echo $this->translate("Client"); ?>
    </th>
    <th>
        <?php echo $this->translate("Bows"); ?>
    </th>
    <th>
        <?php echo $this->translate("Options"); ?>
    </th>
    <?php
        /**  @var  $collection Collection*/
         foreach ($collections as $collection) :
    ?>
        <tr id="collection-<?php echo $collection->getId() ?>">
            <td>
                <?php echo $collection->getReceptionTime() ?>
            </td>
            <td>
                <a href="<?php echo $this->url('client', array('action'=>'details', 'id' => $collection->getOwnerId()));?>">
                    <?php echo $collection->getOwnerName() ?>
                </a>
            </td>
            <td>
                <?php echo $collection->countBows() ?>
            </td>
            <td>
                <a href="<?php
                $params = array('action'=>'details',
                    'id' => $collection->getId(),
                    'clientId' => $collection->getOwnerId(),
                );
                if(!isset($clientId)){
                    $params['section'] = 'list';
                }
                echo $this->url('collection', $params);?>">Details</a>
                <a href="<?php echo $this->url('collection', array('action'=>'edit',
                    'id' => $collection->getId(),
                    'clientId' => $collection->getOwnerId()
                )); ?>">Edit</a>
                <div class="$collection-delete" data-id="<?php echo $collection->getId() ?>" data-section="list" >Delete<div>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<?php
//    $this->placeholder('scripts')->set("
//        BowsManager.client.listInitFilters();
//        BowsManager.client.del();
//    ");
?>