<?php
use Collection\Model\Collection;
use Collection\Enum\CollectionEnum;
use Application\Enum\SectionEnum;

$section = $this->sectionName();

echo ($section == SectionEnum::COLLECTION_INDEX) ? "<h1>" : "<h2>";
?>
    <img src="/img/collection/header.png" <?php echo ($section == SectionEnum::COLLECTION_INDEX) ? "width='80'" : "width='40'"; ?> >
<?php
    echo $this->translate('Collections List');
echo ($section == SectionEnum::COLLECTION_INDEX) ? "</h1>" : "</h2>";
?>
<div class="options">
    <a class="add" href="<?php echo $this->url('collection-add', array(
                                                        'id' => CollectionEnum::NEW_COLLECTION,
                                                        'clientId' => (isset($clientId)) ? $clientId : false,
                                                        'section' => $section,
        )
    );?>">
        <img src="/img/collection/add.png"><?php echo $this->translate("Add new collection"); ?>
    </a>
</div>

<table class="table collections">
    <th>
        <?php echo $this->translate("Reception Date"); ?>
    </th>
    <?php
        if($section == SectionEnum::COLLECTION_INDEX) {
    ?>
        <th><?php echo $this->translate("Client"); ?></th>
    <?php
        }
    ?>
    <th>
        <?php echo $this->translate("Bows"); ?>
    </th>
    <th>
        <?php echo $this->translate("Is sent?"); ?>
    </th>
    <th>&nbsp;</th>
    <?php
        /**  @var  $collection Collection*/
         foreach ($collections as $collection) :
    ?>
        <tr class="collection"
            data-url="<?php echo $this->url('collection-details',  array('id' => $collection->getId(),'section' => $section)); ?>"
            id="collection-<?php echo $collection->getId() ?>">
            <td>
                <?php echo $collection->getReceptionTime() ?>
            </td>
            <?php
            if($section == SectionEnum::COLLECTION_INDEX) {
                ?>
                <td>
                    <a href="<?php echo $this->url('client-details', array('id' => $collection->getOwnerId()));?>">
                        <?php echo $collection->getOwnerName() ?>
                    </a>
                </td>
            <?php
            }
            ?>
            <td class="count-bows">
                <?php echo $collection->countBows() ?>
            </td>
            <td class="count-bows">
                <?php if($collection->isSent()) { ?>
                    <img src="/img/content/valid.png">
                <?php } ?>
            </td>
            <td class="list-options">
                <a class="collection edit" href="<?php echo $this->url('collection-edit', array('id' => $collection->getId(), 'section' => $section)); ?>">
                    <img src="/img/collection/edit.png"><?php echo $this->translate("Edit") ?></a>
                <div class="collection delete" data-id="<?php echo $collection->getId() ?>" >
                    <img src="/img/collection/del.png"><?php echo $this->translate("Delete") ?><div>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<?php
    $this->placeholder('scripts')->append("
        BowsManager.collection.details();
        BowsManager.collection.del();
    ");
?>