<h1><?php echo $this->translate("Client Details") ?></h1>
<div>
    <a href="<?php echo $this->url('client') ?>" >
        <?php $this->translate("Back") ?>
    </a>
    <a href="<?php echo $this->url('client-edit', array('id' => $client->getId()));?>"><?php
       echo $this->translate("Edit")
     ?></a>
    <div class="client-delete" data-id="<?php echo $client->getId() ?>" data-section="<?php echo $this->sectionName() ?>" >
    <?php
       echo $this->translate("Delete")
    ?>
    </div>
</div>
<dl>
    <dt><?php echo $this->translate("Name") ?>:</dt>
    <dd><?php echo $client->getName(false) ?></dd>
    <dt><?php echo $this->translate("Address") ?>:</dt>
    <dd><?php echo $client->getAddress() ?></dd>
</dl>
<dl>
    <dt><?php echo $this->translate("Landline") ?>:</dt>
    <dd><?php echo $client->getLandline() ?></dd>
    <dt><?php echo $this->translate("Mobile") ?>:</dt>
    <dd><?php echo $client->getMobile() ?></dd>
</dl>
<dl>
    <dt><?php echo $this->translate("Email") ?>:</dt>
    <dd>
        <a href="mailto:<?php echo $client->getEmail() ?>" ><?php echo $client->getEmail() ?></a>
    </dd>
    <dt><?php echo $this->translate("Website") ?>:</dt>
    <dd>
        <a href="<?php echo $client->getWebsite() ?>" ><?php echo $client->getWebsite() ?></a>
    </dd>
</dl>
<?php
    // Collection List
    echo $this->partial('collectionList', array(
        'collections' => $client->getCollections(),
        'clientId' => $client->getId()
    ));
?>
<?php
    $this->placeholder('scripts')->append("
        BowsManager.client.del();
    ");
?>