<h1><img src="/img/client/client.png"> <?php echo $header ?></h1>
<a class="back" href="<?php echo $backUrl ?>" ><img src="/img/content/back.png"><?php echo $this->translate("Back") ?></a>
<div class="error-message client"></div>
<form id="client-form" >
    <input type="hidden" name="id" id="id" value="<?php echo $client->getId() ?>">

    <label for="lastName"><?php echo $this->translate("Last Name") ?></label><br />
    <input type="text" name="lastName" id="lastName" value="<?php echo $client->getLastName() ?>"><br />

    <label for="firstName"><?php echo $this->translate("First Name") ?></label><br />
    <input type="text" name="firstName" id="firstName" value="<?php echo $client->getFirstName() ?>"><br />

    <label for="address"><?php echo $this->translate("Address") ?></label><br />
    <textarea name="address" id="address"><?php echo $client->getAddress() ?></textarea><br />

    <label for="landline"><?php echo  $this->translate("Landline") ?></label><br />
    <input type="text" name="landline" id="landline" value="<?php echo $client->getLandline() ?>"><br />

    <label for="mobile"><?php echo $this->translate("Mobile") ?></label><br />
    <input type="text" name="mobile" id="mobile" value="<?php echo $client->getMobile() ?>"><br />

    <label for="email"><?php echo $this->translate("Email") ?></label><br />
    <input type="text" name="email" id="email" value="<?php echo $client->getEmail() ?>"><br />

    <label for="website"><?php echo $this->translate("Website") ?></label><br />
    <input type="text" name="website" id="website" value="<?php echo $client->getWebsite() ?>"><br /><br />

    <div id="save-client">
        <button type="submit"  ><?php echo $this->translate("Save") ?></button>
    </div>
</form>
<?php
    $this->placeholder('scripts')->append("BowsManager.client.add()");
?>


