<?php
use Client\Model\Client;
use Client\Enum\ClientEnum;
?>
<h1><img src="/img/client-back.png"><?php echo $this->translate("Client List"); ?></h1>
<p>
    <a href="<?php echo $this->url('client-add', array('id' => ClientEnum::NEW_CLIENT));?>">
        <?php echo $this->translate("Add new client") ?>
    </a>
</p>

<table class="table">
    <tr>
        <td colspan="2">
        <?php foreach(ClientEnum::FILTERS() as $filter){ ?>
            <a href="#" class="client-filter" id="<?php echo $filter; ?>" ><?php echo $filter; ?></a>
        <?php } ?>
        </td>
    </tr>

    <?php
    $firstLetter = null;
    /**  @var  $client Client*/
    foreach ($clients as $client) :
        $currentFirstLetter = $client->getName();
        if($currentFirstLetter[0] != $firstLetter){
            $firstLetter = $currentFirstLetter[0];
            ?>
            <tr class="data <?php echo $firstLetter ?>">
                <td colspan="3"><h3><?php echo strtoupper($firstLetter);?></h3></td>
            </tr>
        <?php
        }
        ?>
        <tr class="data <?php echo $firstLetter ?>" id="client-<?php echo $client->getId() ?>">
            <td>
                <a href="<?php echo $this->url('client-details', array('id' => $client->getId()));?>">
                    <?php echo $this->escapeHtml($client->getName());?>
                </a>
            </td>
            <td>
               <?php echo $this->translate("Collections") . ": ". $client->countCollections() ?>
            </td>
            <td>
                <a href="<?php echo $this->url('client-edit', array('id' => $client->getId()));?>">
                    <?php echo $this->translate("Edit") ?>
                </a>
                <div class="client-delete" data-id="<?php echo $client->getId() ?>" data-section="<?php echo $this->sectionName();
                ?>" >
                    <?php echo $this->translate("Delete") ?>
                <div>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<?php
    $this->placeholder('scripts')->append("
        BowsManager.client.listInitFilters();
        BowsManager.client.del();
    ");
?>