<?php
use Client\Model\Client;
use Client\Enum\ClientEnum;

$title = 'My clients';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('client', array('action'=>'form', 'id' => ClientEnum::NEW_CLIENT));?>">Add new client</a>
</p>

<table class="table">
    <tr>
        <td colspan="2">
        <?php foreach(ClientEnum::FILTERS() as $filter){ ?>
            <a href="#" class="client-filter" id="<?php echo $filter; ?>" ><?php echo $filter; ?></a>
        <?php } ?>
        </td>
    </tr>

    <?php
        $firstLetter = null;
        /**  @var  $client Client*/
         foreach ($clients as $client) :
            $currentFirstLetter = $client->getName();
            if($currentFirstLetter[0] != $firstLetter){
                $firstLetter = $currentFirstLetter[0];
    ?>
        <tr class="data <?php echo $firstLetter ?>">
            <td colspan="2"><h3><?php echo strtoupper($firstLetter);?></h3></td>
        </tr>
    <?php
            }
    ?>
        <tr class="data <?php echo $firstLetter ?>">
            <td><?php echo $this->escapeHtml($client->getName());?></td>
            <td>
                <a href="<?php echo $this->url('client',
                    array('action'=>'form', 'id' => $client->getId()));?>">Edit</a>
                <a href="<?php echo $this->url('client',
                    array('action'=>'delete', 'id' => $client->getId()));?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<?php
    $this->placeholder('scripts')->set("BowsManager.client.listInitFilters()");
?>