<h1>
    <?php  echo $this->translate("Bow") ?>
</h1>
<div>
    <a href="<?php echo $this->url('collection-details', array('id' => $bow->getCollectionId(), 'section' => $section)) ?>" ><?php echo $this->translate("Back")?></a>
    <a href="<?php echo $this->url('bow-edit', array('id' => $bow->getId(), 'section' => $section));?>">Edit</a>
    <div class="bow-delete" data-id="<?php echo $bow->getId() ?>" data-collectionid="<?php echo $bow->getCollectionId() ?>" data-section="<?php echo $section ?>" >Delete</div>
</div>
<dl>
    <dt>
        <?php echo $this->translate("Type") ?>
    </dt>
    <dd>
        <?php echo $this->translate(\Bow\Enum\BowTypeEnum::COPY($bow->getType())) ?>
    </dd>
    <dt>
        <?php echo $this->translate("Size") ?>
    </dt>
    <dd>
        <?php echo  $this->translate(\Bow\Enum\BowSizeEnum::COPY($bow->getSize())) ?>
    </dd>
    <dt>
        <?php echo $this->translate("Description") ?>
    </dt>
    <dd>
        <?php echo $bow->getDescription() ?>
    </dd>
    <dt>
        <?php echo $this->translate("Work to do") ?>
    </dt>
    <dd>
        <?php echo $bow->getWorkToDo() ?>
    </dd>
    <dt>
        <?php echo $this->translate("Status") ?>
    </dt>
    <dd>
        <?php echo $bow->getStatus() ?>
    </dd>
    <dt>
        <?php echo $this->translate("Is done?") ?>
    </dt>
    <dd>
        <?php echo ($bow->getIsDone()) ? "Done" : "Not Done" ?>
    </dd>
    <dt>
        <?php echo $this->translate("Comments") ?>
    </dt>
    <dd>
        <?php echo $bow->getComments() ?>
    </dd>
</dl>
<?php
$this->placeholder('scripts')->append("
        BowsManager.bow.del();
    ");
?>