<?php
use Bow\Model\Bow;
use Bow\Enum\BowTypeEnum;
use Bow\Enum\BowSizeEnum;

?>
<h2><?php echo $this->translate("Bows List"); ?></h2>
<p>
    <a href="<?php
        echo $this->url('bow-add', array('collectionId' => $collectionId, 'section' => $section));
    ?>"><?php
        echo $this->translate("Add new bow")
    ?></a>
</p>

<table class="table bows">
    <tr>
        <th><?php echo $this->translate("Type") ?></th>
        <th><?php echo $this->translate("Size") ?></th>
        <th><?php echo $this->translate("Description") ?></th>
        <th><?php echo $this->translate("Work to do") ?></th>
        <th><?php echo $this->translate("Status") ?></th>
        <th><?php echo $this->translate("Is done?") ?></th>
        <th><?php echo $this->translate("Comments") ?></th>
        <th>&nbsp;</th>
    </tr>

    <?php /**  @var  $bow Bow*/?>
    <?php foreach ($bows as $bow) : ?>
        <?php $detailUrl = $this->url('bow-details', array('id' => $bow->getId(), 'section' => $section)); ?>
        <tr class="bow" id="bow-<?php echo $bow->getId() ?>" data-url="<?php echo $detailUrl ?>" >
            <td><?php echo $this->translate(BowTypeEnum::COPY($bow->getType()));?></td>
            <td><?php echo $this->translate(BowSizeEnum::COPY($bow->getSize()));?></td>
            <td><?php echo $this->escapeHtml($bow->getDescription());?></td>
            <td><?php echo $this->escapeHtml($bow->getWorkToDo());?></td>
            <td><?php echo $this->escapeHtml($bow->getStatus());?></td>
            <td><?php echo $this->escapeHtml($bow->getIsDone());?></td>
            <td><?php echo $this->escapeHtml($bow->getComments());?></td>
            <td>
                <a class="edit" href="<?php echo $this->url('bow-edit', array('id' => $bow->getId(), 'section' => $section));?>"><?php echo $this->translate("Edit") ?></a>
                <div class="bow delete" data-id="<?php echo $bow->getId() ?>" ><?php echo $this->translate("Delete") ?><div>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<?php
$this->placeholder('scripts')->append("
        BowsManager.bow.details();
        BowsManager.bow.del();
    ");
?>