<?php
use Bow\Model\Bow;
use Bow\Enum\BowTypeEnum;
use Bow\Enum\BowSizeEnum;

?>
<h2><img src="/img/bow/header.png" width="50" /> <?php echo $this->translate("Bows List"); ?></h2>
<div class="options">
    <a class="add" href="<?php
    echo $this->url('bow-add', array('collectionId' => $collectionId, 'section' => $section));
    ?>"><img src="/img/bow/add.png" /><?php
        echo $this->translate("Add new bow")
        ?></a>
</div>
<div class="error-message bow"></div>

<table class="table bows">
    <tr>
        <th><?php echo $this->translate("Type") ?></th>
        <th><?php echo $this->translate("Size") ?></th>
        <th><?php echo $this->translate("Description") ?></th>
        <th><?php echo $this->translate("Work to do") ?></th>
        <th><?php echo $this->translate("Status") ?></th>
        <th><?php echo $this->translate("Is done?") ?></th>
        <th><?php echo $this->translate("Comments") ?></th>
        <th><?php echo $this->translate("Attachment") ?></th>
        <th>&nbsp;</th>
    </tr>

    <?php /**  @var  $bow Bow*/?>
    <?php foreach ($bows as $bow) : ?>
        <?php $detailUrl = $this->url('bow-details', array('id' => $bow->getId(), 'section' => $section)); ?>
        <tr class="bow" id="bow-<?php echo $bow->getId() ?>" data-url="<?php echo $detailUrl ?>" >
            <td><?php echo $this->translate(BowTypeEnum::COPY($bow->getType()));?></td>
            <td><?php echo $this->translate(BowSizeEnum::COPY($bow->getSize()));?></td>
            <td><?php echo nl2br($bow->getDescription());?></td>
            <td><?php echo nl2br($bow->getWorkToDo());?></td>
            <td><?php echo nl2br($bow->getStatus());?></td>
            <td>
                <?php if($bow->getIsDone()) { ?>
                    <img src="/img/content/valid.png">
                <?php } ?>
            </td>
            <td><?php echo nl2br($bow->getComments());?></td>
            <td>
                <?php if($bow->hasAttachments()) { ?>
                    <img src="/img/content/attachment.png">
                <?php } ?>
            </td>
            <td class="list-options">
                <a class="edit" href="<?php echo $this->url('bow-edit', array('id' => $bow->getId(), 'section' => $section));?>"><img src="/img/bow/edit.png" /></a>
                <div class="bow delete" data-id="<?php echo $bow->getId() ?>" ><img src="/img/bow/del.png" /><div>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<?php
$this->placeholder('scripts')->append("
        BowsManager.bow.details();
        BowsManager.bow.del();
    ");
?>