<?php
use Application\Enum\SectionEnum;
    echo $this->doctype();
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Bows Manager')) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/css/bowsmanager-responsive.css')
            ->prependStylesheet($this->basePath() . '/css/bowsmanager.css')
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/jquery-ui-1.10.3.custom.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bowsmanager.js')
            ->prependFile($this->basePath() . '/js/lib/plugins.js')
            ->prependFile($this->basePath() . '/js/lib/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/lib/jquery-ui-1.10.3.custom.min.js')
            ->prependFile($this->basePath() . '/js/lib/jquery.min.js')
            ->prependFile($this->basePath() . '/js/lib/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/lib/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" <?php echo ($_SERVER['APPLICATION_ENV'] == 'development') ? "style='color: red'" : ""; ?>" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/bm-logo.png') ?>" alt="Bows Manager"/>&nbsp;<?php echo $this->translate('Bows Manager') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                        <?php
                            $supplierSubNav = array(
                                array('class' => 'supplier', 'label' => "Suppliers" ,'url' => 'supplier', 'sections' => array(SectionEnum::SUPPLIER),),
                                array('class' => 'product', 'label' => "Products" ,'url' => 'product-type', 'sections' => array(SectionEnum::PRODUCT_TYPE, SectionEnum::PRODUCT),),
                            );

                            $navigation = array(
                                array('class' => 'home', 'label' => "Home" ,'url' => 'home', 'sections' => array(SectionEnum::HOME)),
                                array('class' => 'client', 'label' => "Clients" ,'url' => 'client', 'sections' => array(SectionEnum::CLIENT)),
                                array('class' => 'collection', 'label' => "Collections" ,'url' =>'collection', 'sections' => array(SectionEnum::COLLECTION, SectionEnum::BOW)),
                                array('class' => 'bill', 'label' => "Bills" ,'url' =>'bill', 'sections' => array(SectionEnum::BILL)),
                                array('class' => 'supplier-section dropdown', 'label' => "Suppliers" , 'sections' => array(SectionEnum::SUPPLIER, SectionEnum::PRODUCT, SectionEnum::PRODUCT_TYPE), 'id' => 'supplier', 'subNav' => $supplierSubNav),
                                array('class' => 'search', 'label' => "Search" ,'url' => 'search', 'sections' => array(SectionEnum::SEARCH)),
                            );

                            $currentSectionName = $this->sectionName();
                            foreach($navigation as $element){
                                $active = "";
                                foreach($element["sections"] as $section){
                                    if(strpos($currentSectionName, $section) !== false){
                                        $active = " active";
                                    }
                                }
                        ?>
                                <li class="<?php echo $active; ?>">
                                    <?php if(!empty($element['subNav'])) { ?>
                                        <a id="<?php echo $element["id"]; ?>" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">
                                            <span class="icon <?php echo $element["class"]; ?>"></span>
                                            <?php echo $this->translate($element["label"]); ?>
                                            <b class="caret"></b>
                                        </a>
                                        <ul class="dropdown-menu" role="menu" aria-labelledby="<?php echo $element["id"]; ?>">
                                            <?php foreach($element['subNav'] as $subNavElement){
                                                        $subActive = "";
                                                        foreach($subNavElement["sections"] as $section){
                                                            if(strpos($currentSectionName, $section) !== false){
                                                                $subActive = " active";
                                                            }
                                                        }
                                                ?>
                                                <li class="<?php echo $subActive; ?>" role="presentation">
                                                    <a role="menuitem" tabindex="-1" href="<?php echo $this->url($subNavElement["url"]) ?>"><span class="icon <?php echo $subNavElement["class"]; ?>"></span><?php echo $this->translate($subNavElement["label"]) ?></a>
                                                </li>
                                            <?php } ?>
                                        </ul>
                                    <?php } else { ?>
                                        <a href="<?php echo $this->url($element["url"]); ?>">
                                            <span class="icon <?php echo $element["class"]; ?>"></span>
                                            <?php echo $this->translate($element["label"]); ?>
                                        </a>
                                    <?php } ?>
                                </li>
                        <?php
                            }
                        ?>
                        </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
<!--            <hr>-->
<!--            <footer>-->
<!--            </footer>-->
        </div> <!-- /container -->
        <?php
            echo $this->inlineScript();
            echo $this->partial('jsCopies');
            echo "<script type='text/javascript'>" . $this->placeholder('scripts') . "</script>";
        ?>
    </body>
</html>
