<?php
use Bill\Model\Bill;
use Bill\Enum\BillPaymentTypeEnum;
use Application\Enum\SectionEnum;

if($section == SectionEnum::BILL_INDEX){
?>
    <h1>
        <img src="/img/bill/header.png" width='80' /> <?php echo $this->translate($header); ?>
    </h1>
<?php
}
else {
    ?>
    <h2>
        <img src="/img/bill/header.png" width='40' /> <?php echo $this->translate($header); ?>
    </h2>
<?php
}
?>
<div class="options">
    <div class="bill add" data-collection="<?php echo \Bill\Enum\BillEnum::NO_COLLECTION ?>"  data-section="<?php echo $section ?>" ><img src="/img/bill/add.png" /><?php echo $this->translate("Add new bill") ?></div>
</div>
<div class="error-message bill"></div>

<?php foreach ($bills as $year => $billList) { ?>
<h3 class="display-bill-list" data-year="<?php echo $year; ?>" ><?php echo $year . " (" . count($billList) . ")"?> </h3>
<table id="bill-list-<?php echo $year; ?>" class="table bills" <?php echo  date("Y") != $year ? "style='display: none'": ""; ?>>
    <tr>
        <th><?php echo $this->translate("Reference") ?></th>
        <th><?php echo $this->translate("Amount") ?></th>
        <th><?php echo $this->translate("Is paid?") ?></th>
        <th><?php echo $this->translate("Attachment") ?></th>
        <th>&nbsp;</th>
    </tr>

    <?php /**  @var  $bill Bill*/?>
    <?php foreach ($billList as $bill) : ?>
        <tr class="bill" id="bill-<?php echo $bill->getId() ?>" data-id="<?php echo  $bill->getId() ?>" data-section="<?php echo $section ?>" >
            <td><?php echo $bill->getReference(); ?></td>
            <td><?php echo $bill->getAmount(true); ?> €</td>
            <td class="<?php echo ($bill->isPaid()) ? "": "bill-is-paid"; ?>"   >
                <?php
                if($bill->isPaid()){
                    ?>
                    <img src="/img/content/valid.png" />
                <?php
                }
                else {
                    ?>
                    <div data-toggle='modal' data-target='#confirm-payment-<?php echo $bill->getId() ?>'>
                        <img src="/img/content/invalid.png"  />
                    </div>
                <?php
                }
                ?>

                <div class="modal fade confirm-payment" id="confirm-payment-<?php echo $bill->getId() ?>" tabindex="-1" role="dialog"  aria-hidden="true" data-id="<?php echo $bill->getId() ?>">
                    <div class="modal-dialog">
                        <div class="modal-content">

                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-labelledby="bmBillModalLabel" aria-hidden="true">&times;</button>
                                <h4 class="modal-title" id="bmBillModalLabel"><?php echo $this->translate("Confirm Payment"); ?></h4>
                            </div>

                            <div class="modal-body">
                                <p><?php echo $this->translate("Is that bill really paid?") ?></p>
                                <p><?php echo $this->translate("What is the type of payment?") ?></p>
                                <?php
                                foreach(BillPaymentTypeEnum::TYPES(true) as $value => $type) {
                                    ?>
                                    <label class="radio-inline">
                                        <input type="radio" name="payment-type" value="<?php echo $value ?>" ><?php echo $this->translate($type) ?>
                                    </label>
                                    <?php
                                }
                                ?>
                            </div>

                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate("Cancel"); ?></button>
                                <a class="btn btn-success btn-ok"><?php echo $this->translate("Validate"); ?></a>
                            </div>
                        </div>
                    </div>
                </div>

            </td>
            <td>
                <?php if($bill->hasAttachments()) { ?>
                    <img src="/img/content/attachment.png">
                <?php } ?>
            </td>
            <td class="bill-options">
                <div class="list-options" >
                    <div class="bill delete" data-id="<?php echo $bill->getId() ?>" ><img src="/img/bill/del.png" /><?php echo $this->translate("Delete") ?></div>
                    <div class="bill edit" data-id="<?php echo $bill->getId() ?>"  data-section="<?php echo $section ?>" ><img src="/img/bill/edit.png" /><?php echo $this->translate("Edit") ?></div>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<?php } ?>


<?php
$this->placeholder('scripts')->append("
        BowsManager.bill.filters();
        BowsManager.bill.details();
        BowsManager.bill.del();
        BowsManager.bill.add();
        BowsManager.bill.edit();
        BowsManager.bill.paid();
    ");
?>