<?php
use Bow\Model\Bow;
use Bow\Enum\BowTypeEnum;
use Bow\Enum\BowSizeEnum;
?>
<h2><?php echo $this->translate("Bows") ?></h2>
<table class="table">
    <tr>
        <th><?php echo $this->translate("Type") ?></th>
        <th><?php echo $this->translate("Size") ?></th>
        <th><?php echo $this->translate("Description") ?></th>
        <th><?php echo $this->translate("Work to do") ?></th>
        <th><?php echo $this->translate("Status") ?></th>
        <th><?php echo $this->translate("Is done?") ?></th>
        <th><?php echo $this->translate("Comments") ?></th>
        <th>&nbsp;</th>
    </tr>

    <?php /**  @var  $bow Bow*/?>
    <?php foreach ($bows as $bow) : ?>
        <tr id="bow-<?php echo $bow->getId() ?>" >
            <td><?php echo $this->highLight($this->translate(BowTypeEnum::COPY($bow->getType())), $query);?></td>
            <td><?php echo $this->highLight($this->translate(BowSizeEnum::COPY($bow->getSize())), $query);?></td>
            <td><?php echo $this->highLight($bow->getDescription(), $query);?></td>
            <td><?php echo $this->highLight($bow->getWorkToDo(), $query);?></td>
            <td><?php echo $this->highLight($bow->getStatus(), $query);?></td>
            <td><?php echo $bow->getIsDone() ?></td>
            <td><?php echo $this->highLight($bow->getComments(), $query);?></td>
            <td>
                <a href="<?php echo $this->url('bow-details', array('id' => $bow->getId()));?>"><?php echo $this->translate("Details") ?></a>
                <a href="<?php echo $this->url('bow-edit', array('id' => $bow->getId()));?>"><?php echo $this->translate("Edit") ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
