<h2><img src="/img/client/header.png" width="50" /><?php echo $this->translate("Clients") ?></h2>
<table class="table clients">

<?php
$firstLetter = null;
/**  @var  $client Client*/
foreach ($clients as $client) :
    $currentFirstLetter = strtolower($client->getName());
    if($currentFirstLetter[0] != $firstLetter){
        $firstLetter = $currentFirstLetter[0];
        ?>
        <tr class="data <?php echo $firstLetter ?>">
            <td colspan="3"><h4><b><?php echo strtoupper($firstLetter);?></b></h4></td>
        </tr>
    <?php
    }
    ?>
    <?php
    $detailUrl =  $this->url('client-details', array('id' => $client->getId()));
    ?>
    <tr class="data client <?php echo $firstLetter ?>" id="client-<?php echo $client->getId() ?>" data-url="<?php echo $detailUrl ?>" >
        <td><?php echo $this->highLight($client->getName(), $query); ?>
        </td>
        <td><?php echo $this->translate("Collections") ?>: <?php echo $client->countCollections() ?></td>
        <td class="list-options">
            <a class="client edit" href="<?php echo $this->url('client-edit', array('id' => $client->getId()));?>">
                <img src="/img/client/edit.png"><?php echo $this->translate("Edit") ?></a>
            <div class="client delete" data-id="<?php echo $client->getId() ?>" data-section="<?php echo $this->sectionName();
            ?>" > <img src="/img/client/del.png"><?php echo $this->translate("Delete") ?>
            </div>
        </td>
    </tr>
<?php endforeach; ?>

</table>
