<h2><?php echo $this->translate("Clients") ?></h2>
<?php
$firstLetter = null;
/**  @var  $client Client*/
foreach ($clients as $client) :
    $currentFirstLetter = $client->getName();
    if($currentFirstLetter[0] != $firstLetter){
        $firstLetter = $currentFirstLetter[0];
        ?>
        <tr class="data <?php echo $firstLetter ?>">
            <td colspan="3"><h4><?php echo strtoupper($firstLetter);?></h4></td>
        </tr>
    <?php
    }
    ?>
    <tr class="data <?php echo $firstLetter ?>" id="client-<?php echo $client->getId() ?>">
        <td>
            <a href="<?php echo $this->url('client-details', array('id' => $client->getId()));?>"><?php
                    echo $this->highLight($client->getName(), $query);
            ?></a>
        </td>
        <td>
            <?php echo $this->translate("Collections") ?>: <?php echo $client->countCollections() ?>
        </td>
        <td>
            <a href="<?php echo $this->url('client-details',array('id' => $client->getId()));?>">
                <?php echo $this->translate("Details") ?></a>
            <a href="<?php echo $this->url('client-edit', array('id' => $client->getId()));?>"><?php echo $this->translate("Edit") ?></a>
        </td>
    </tr>
<?php endforeach; ?>