<?php
use Collection\Model\Collection;
use Collection\Enum\CollectionEnum;

$title = 'My search';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<form id="search-form" >
    <input type="text" name="query" />
    <select name="type" multiple>
        <option selected="selected" value="client">Client</option>
        <option selected="selected"value="bow">Archet</option>
        <option selected="selected" value="collection">Lot</option>
    </select>
    <button type="submit" id="search">Rechercher</button>
</form>
<div class="error-message"></div>
<div id="client-results"></div>
<div id="bow-results"></div>
<?php
    $this->placeholder('scripts')->set("BowsManager.search.search()");
?>
