<div class="collection-list">
<?php echo $this->partial('collectionList', array('collections' => $collectionsNotSent,
                                                    'header' => 'Collections Not Sent',)); ?>
</div>
<div class="collection-list">
    <?php echo $this->partial('collectionList', array('collections' => $collectionsNotPaid,
                                                    'header' => 'Collections Not Paid',)); ?>
</div>