<div class="collection-list">
<?php echo $this->partial('collectionList', array('collections' => $collectionsNotSent,
                                                    'header' => 'Collections Not Sent',)); ?>
</div>
<div class="bill-list">
    <?php echo $this->partial('billList', array('bills' => $billsNotPaid,
                                                    'header' => 'Bills Not Paid',
                                                    'section' => \Application\Enum\SectionEnum::HOME)); ?>
</div>