<?php
$loading = $this->translate("Loading...");

$deleteClient = $this->translate("Do you really want to delete this client, his collections and bows?");

$deleteBow = $this->translate("Do you really want to delete this bow?");
$isDoneBow = $this->translate("Is that bow really done?");

$deleteCollection = $this->translate("Do you really want to delete this collection and bows relative to it?");

$deleteBill = $this->translate("Do you really want to delete this bill?");
$isBillPaid = $this->translate("Is that bill really paid?");

$deleteSupplier = $this->translate("Do you really want to delete this supplier?");

?>
<script type='text/javascript'>
    BowsManager.copies = {
        loading:  "<?php echo $loading ?>",
        deleteClient: "<?php echo $deleteClient ?>",
        deleteBow: "<?php echo $deleteBow ?>",
        isDoneBow: "<?php echo $isDoneBow ?>",
        deleteCollection: "<?php echo $deleteCollection ?>",
        deleteBill: "<?php echo $deleteBill ?>",
        isBillPaid: "<?php echo $isBillPaid ?>",
        deleteSupplier: "<?php echo $deleteSupplier ?>"
    };
</script>
