<?php
$loading = $this->translate("Loading...");

$deleteClient = $this->translate("Do you really want to delete this client, his collections and bows?");

$deleteBow = $this->translate("Do you really want to delete this bow?");
$isDoneBow = $this->translate("Is that bow really done?");
$allDoneBows = $this->translate("All done?");

$deleteCollection = $this->translate("Do you really want to delete this collection and bows relative to it?");

$deleteBill = $this->translate("Do you really want to delete this bill?");

$deleteSupplier = $this->translate("Do you really want to delete this supplier?");
$deleteProduct = $this->translate("Do you really want to delete this product?");
$deleteProductType = $this->translate("Do you really want to delete this product type?");

?>
<script type='text/javascript'>
    BowsManager.copies = {
        loading:  "<?php echo $loading ?>",
        deleteClient: "<?php echo $deleteClient ?>",
        deleteBow: "<?php echo $deleteBow ?>",
        isDoneBow: "<?php echo $isDoneBow ?>",
        allDoneBows: "<?php echo $allDoneBows ?>",
        deleteCollection: "<?php echo $deleteCollection ?>",
        deleteBill: "<?php echo $deleteBill ?>",
        deleteSupplier: "<?php echo $deleteSupplier ?>",
        deleteProduct: "<?php echo $deleteProduct ?>",
        deleteProductType: "<?php echo $deleteProductType ?>"
    };
</script>
